# Generated by Django 5.0.4 on 2024-04-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', models.TextField(verbose_name='About Text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
