# Generated by Django 5.0.4 on 2024-04-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
