# Generated by Django 5.0.4 on 2024-04-24 18:37

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_aboutpage_about_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessfulGoalPlanningInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
                ('is_active', models.BooleanField(verbose_name='Is Active')),
            ],
        ),
        migrations.CreateModel(
            name='SuggestionsForSuccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
                ('is_active', models.BooleanField(verbose_name='Is Active')),
            ],
        ),
        migrations.CreateModel(
            name='UnderstandingGoalPrioritization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_active', models.BooleanField(verbose_name='Is Active')),
            ],
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='about_text',
            field=tinymce.models.HTMLField(verbose_name='About Text'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='is_active',
            field=models.BooleanField(verbose_name='Is Active'),
        ),
    ]
