# Generated by Django 5.0.4 on 2024-04-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_successfulgoalplanninginstruction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='understandinggoalprioritization',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='successfulgoalplanninginstruction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='suggestionsforsuccess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='understandinggoalprioritization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
