# Generated by Django 5.0.4 on 2024-04-26 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_goalsettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goalsettings',
            old_name='goal_to_achive',
            new_name='goal_to_achieve',
        ),
    ]
