# Generated by Django 5.0.4 on 2024-04-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_goal_to_achive_goalsettings_goal_to_achieve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalsettings',
            name='goal_term',
            field=models.CharField(choices=[('Short Term', 'Short Term'), ('Long Term', 'Long Term')], max_length=20),
        ),
        migrations.AlterField(
            model_name='goalsettings',
            name='priority_scale',
            field=models.CharField(choices=[('Low', 'Low'), ('Med', 'Med'), ('High', 'High')], max_length=20),
        ),
        migrations.AlterField(
            model_name='goalsettings',
            name='target_completion_date',
            field=models.DateTimeField(),
        ),
    ]
