# Generated by Django 5.0.4 on 2024-04-30 04:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_goalsettings_goal_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalsettings',
            name='goal_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goalsettings',
            name='progress_accomplishment',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goalsettings',
            name='status',
            field=models.CharField(blank=True, choices=[('All', 'All'), ('In Progress', 'In Progress'), ('Complated', 'Complated')], null=True),
        ),
        migrations.AddField(
            model_name='goalsettings',
            name='stebacks',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goalsettings',
            name='what_will_do_next',
            field=models.CharField(blank=True, null=True),
        ),
    ]
