# Generated by Django 5.0.4 on 2024-05-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_link_is_share_app_link_share_app_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='platform',
            field=models.CharField(choices=[('All', 'All Platforms'), ('iOS', 'iOS'), ('Android', 'Android')], default='All', max_length=50),
        ),
    ]
