# Generated by Django 5.0.4 on 2026-02-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_link_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='status',
        ),
        migrations.AddField(
            model_name='goalsettings',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed')], default='In Progress', max_length=20),
        ),
    ]
