# Generated by Django 5.0.4 on 2026-02-07 07:52

from django.db import migrations


def set_initial_status(apps, schema_editor):
    GoalSettings = apps.get_model('api', 'GoalSettings')
    
    # Set all goals without a status to 'In Progress'
    updated = GoalSettings.objects.filter(status__isnull=True).update(status='In Progress')
    print(f"Updated {updated} goals to 'In Progress' status")
    
    # Alternative: Set status to 'In Progress' for all existing goals
    # updated = GoalSettings.objects.all().update(status='In Progress')


def reverse_set_initial_status(apps, schema_editor):
    # Optional: Define reverse operation if needed
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_progress_status_goalsettings_status'),
    ]

    operations = [
        migrations.RunPython(set_initial_status, reverse_set_initial_status),
    ]
